@startuml classUML

title Class UML Diagram

Task "*" -- "1" Board : tasks
Task "*" -- "1" Database
Board "*" -- "1" Database
Board "*" -- "1" UI
Task "*" -- "1" UI
UI "1" -- "1" Database

enum Stage {
  ToDo
  InProgress
  Done
}

class Task {
  -id: int
  -title: string
  -description: string
  -stage: Stage
  -difficultyRating: int
  +Task(title: string, board: Board&)
  +~Task()
  +setId(id: int): void
  +setTitle(newTitle: string): void
  +setDescription(newDesc: string): void
  +setStage(newStage: Stage): void
  +setDifficultyRating(rating: int): void
  +getId(): int
  +getTitle(): string
  +getDescription(): string
  +getStage(): Stage
  +getDifficultyRating(): int
  +stageToString(stage: Stage): string
  +stringToStage(stageStr: string): Stage
}

class Board {
  -id: int
  -title: string
  -tasks: list<Task*>
  +Board(title: string)
  +~Board()
  +setId(id: int): void
  +setTitle(newTitle: string): void
  +addTask(task: Task&): void
  +removeTask(task: Task&): void
  +getId(): int
  +getTitle(): string
  +getTasks(): list<Task*>
  +findById(boards: list<Board*>, id: int): Board*
}

class UI {
  -TEXT_WHITE: WORD
  -TEXT_GREEN: WORD
  -db: Database
  -loadedBoards: list<Board*>
  -loadedTasks: list<Task*>
  -selectedBoard: Board
  -selectedTask: Task
  -selectedIndex: int
  -currScreen: string
  -screenMenus: map<string, string>
  +UI(db: Database&)
  +setTextColor(color: WORD): void
  +setSelectIndex(index: int): void
  +loadBoards(): void
  +loadTasks(): void
  +getSelectedBoardAndLoadTasks(): void
  +getSelectedTask(): void
  +displayScreen(): void
  +displayTitles(titles: list<string>&): void
  +displayTaskCard(taskDetails: string): void
  +addNewBoard(): void
  +addNewTask(): void
  +removeSelectedBoard(): void
  +removeSelectedTask(): void
  +getUserInput(prompt: string): string
  +keyboardListen(): void
  +changeSelector(direction: int): void
  +changeScreen(command: string): void
  +editBoardTitle(): void
  +editTaskDescription(): void
  +editTaskTitle(): void
  +editTaskStage(): void
  +editTaskRating(): void
}

class Database {
  -dbName: string
  -db: sqlite3*
  +Database(dbName: string)
  +~Database()
  +createTables(): void
  +deleteTables(): void
  +executeQuery(sql: string, dataMap: map<string, variant<int, string>>): int
  +queryString(tableName: string, dataMap: map<string, variant<int, string>>): string
  +saveBoardData(board: Board&): void
  +saveTaskData(task: Task&): void
  +loadBoardData(): list<Board*>
  +loadTaskData(boards: list<Board*>): list<Task*>
  +deleteTask(task: Task&): void
  +deleteBoard(board: Board&): void
}

@enduml
