@startuml sequenceDiagram

title Sequence Diagram

actor User
participant "UI" as UI
participant "Task" as T
participant "Board" as B
participant "Database" as DB

'Initial load Boards list
note over User, DB: Display all Boards
User -> UI: reloadBoards()
activate UI
UI -> DB: loadBoardsList()
activate DB
DB -> UI: loadedBoards
deactivate DB
UI --> User: displayScreen()
deactivate UI

'Create new Board
note over User, DB: Add Board
alt User creates a new Board
  User -> UI: addNewBoard()
  activate UI
  UI -> B: addNewBoard()
  activate B
  B -> DB: saveBoardData()
  activate DB
  deactivate B
  deactivate DB
  UI -> DB: reloadBoards()
  activate DB
  DB -> UI: loadedBoards
  deactivate DB
  UI --> User: displayScreen()
  deactivate UI
end

'Rename Board title
note over User, DB: Rename Board
User -> UI: editBoardTitle()
activate UI
UI -> B: setTitle()
activate B
B -> DB: saveBoardData()
activate DB
deactivate B
deactivate DB
UI -> DB: reloadBoards()
activate DB
DB -> UI: loadedBoards
deactivate DB
UI --> User: displayScreen()
deactivate UI

'Open Board
note over User, DB: Open Board
User -> UI: changeScreen() "Board View"
activate UI
UI -> B: reloadBoardTasks()
activate B
B -> DB: loadTaskData()
activate DB
DB -> B: setTasks()
deactivate DB
deactivate B
UI --> User: displayScreen()
deactivate UI

'Create new Task
note over User, DB: Add Task
alt User creates a new Task
  User -> UI: addNewTask()
  activate UI
  UI -> T: Task()
  activate T
  T -> DB: saveTaskData()
  activate DB
  deactivate T
  deactivate DB
  UI -> DB: reloadBoardTasks()
  activate B
  activate DB
  DB -> B: setTasks()
  deactivate B
  deactivate DB
  UI --> User: displayScreen()
  deactivate UI
end

'Delete Task
note over User, DB: Delete Task
User -> UI: deleteSelectedTask()
activate UI
UI -> B: getBoardById()
activate B
B -> T: getTasks()
deactivate B
activate T
T -> DB: deleteTask()
activate DB
deactivate T
deactivate DB
UI -> DB: reloadBoardTasks()
activate B
activate DB
DB -> B: setTasks()
deactivate B
deactivate DB
UI --> User: displayScreen()
deactivate UI

'Open Task
note over User, DB: Open Task
User -> UI: changeScreen() "Task View"
activate UI
UI -> B: findSelectedTask();
activate B
B -> T: getTasks()
deactivate B
activate T
T -> UI: activeTaskId
deactivate T
UI --> User: displayScreen()
deactivate UI

'Edit Task Stages
note over User, DB: Edit Task
User -> UI: editTaskStage() "In Progress"
activate UI
alt Task has description and difficulty
  UI -> T: editTaskStage()
  activate T
  T -> DB: saveTaskData()
  activate DB
  DB --> T: confirm
  deactivate DB
else Task missing description or difficulty
  T --> UI: error() 
  deactivate T
  User -> UI: editTaskDescription()
  UI -> T: setDescription()
  activate T
  T -> DB: saveTaskData()
  activate DB
  DB --> T: confirm
  deactivate T
  deactivate DB
  User -> UI: editTaskRating()
  UI -> T: setDifficulty()
  activate T
  T -> DB: saveTaskData()
  activate DB
  DB --> T: confirm
  deactivate T
  deactivate DB
  UI -> T: editTaskStage()
  activate T
  T -> DB: saveTaskData()
  activate DB
  DB --> T: confirm
  deactivate DB
  deactivate T
end

UI -> DB: reloadBoardTasks()
activate DB
DB -> B: setTasks()
activate B
deactivate B
deactivate DB
UI --> User: displayScreen()
deactivate UI

User -> UI: editTaskStage() "Done"
activate UI
UI -> T: editTaskStage()
activate T
T -> DB: saveTaskData()
activate DB
DB --> T: confirm
deactivate T
deactivate DB
UI -> DB: reloadBoardTasks()
activate DB
DB -> B: setTasks()
activate B
deactivate B
deactivate DB
UI --> User: displayScreen()
deactivate UI

'Delete Board
note over User, DB: Delete Board
User -> UI: deleteSelectedBoard()
activate UI
UI -> DB: deleteSelectedBoard()
activate DB
activate T
T -> DB: delete associated Tasks
deactivate T
deactivate DB
UI -> DB: reloadBoards()
activate DB
DB -> UI: loadedBoards
deactivate DB
UI --> User: displayScreen()
deactivate UI

@enduml
